### ISSUE TITLE
Hangs with YAML files in ST3 build 3067

### ISSUE THREAD

**Issue by joemaller** [facelessuser/BracketHighlighter#220]
This took me a little while to nail down, but I am able to reproduce it 100% of the time on multiple Macs.  

Starting from a clean installation of Sublime Text 3 build 3067.

#### Normal
1. Create new document
2. `Set Syntax: YAML`
3. Type this into the new document: `foo: bar`

Result: No problems.

#### Beachballs
1. Install **Package Control**
2. Install **BracketHighlighter**
3. Create a new document
4.  `Set Syntax: YAML`
5. Type this into the new document: `foo: bar`

Result: :skull: Spinning Beach Ball of Death, usually right after the colon. 

Worse still, when reopening ST3 after force-quitting, the file will re-open and almost immediately hang again.

Note, on my Mac I completely nuked my Sublime Text config by removing `~/Library/Application Support/Sublime Text 3/`. The second test mac was a clean install of Sublime Text. I don't have Windows or Linux GUI to test on.

**Comment by facelessuser** [comment]
Is this a new thing since 3067?  Or something that has existed before 3067?

**Comment by joemaller** [comment]
So far as I know, it started today with build 3067. I installed that and my YAML files started hanging. I've had BracketHighlighter installed forever...

btw, I tested on was on 10.10.2 and 10.9.5

**Comment by facelessuser** [comment]
This has got to be new.  If in JSON, you can do this and get a hang as well:

```js
{
    ""
```
This is no good :frowning:.

It appears to be related to the scope (in this case string) being at the end of the file.  By adding a few newlines and then doing adding the curly and string, there is no hang.

Sublime has changed something, and and now it appears some of my previous assumptions are causing problems.

I may get time this weekend to solve it, but maybe not.  I am still not certain there is anything inherently wrong with what I am doing.  It may just be a Sublime bug, but first I have to narrow down what *exactly* causes the hang.

**Comment by facelessuser** [comment]
One more bit of info.  This appears to something specifically related to bracket_scope (double quote matching etc.).  Disabling all `bracket_scope` rules removes the issue.

At least my suspicions of scope related issues are confirmed.  I will try and narrow down what specifically I am doing with scopes that is causing the issue this weekend (depending on the difficulty of isolating the problem and how much time I have).  Hopefully it is something I can work around.

**Comment by joemaller** [comment]
fyi, can't ask for a better source: 

>  there has indeed been a change to selector matching at EOF: previously it would return the default scope, whereas now it returns whatever scope is used by the last character. This improves auto complete behavior when typing at EOF, and is more in line with general expectations, e.g., consider a Python file consisting of nothing but the 3 characters '#foo': the scope returned when querying at EOF now indicates that EOF is in a comment, whereas before it would just indicate 'source.python'.

http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17470&start=40#p65416

**Comment by facelessuser** [comment]
Yes, this is what I have been discovering.  I have the hang fixed, but now I am working on fixing how matching at EOF works as well.

**Comment by facelessuser** [comment]
Commit https://github.com/facelessuser/BracketHighlighter/commit/6ce6e3de7845be9f4fe7db48b7221efbb480c725 should fix this issue.  Let me know.

**Comment by ingro** [comment]
I still have problem in javascript files, as soon as I open a bracket to write a string ST3 hangs :/

**Comment by facelessuser** [comment]
> I still have problem in javascript files, as soon as I open a bracket to write a string ST3 hangs :/

I do not see this issue anymore.  I have tried strings in Javascript, Python, Yaml, JSON, etc.  and they are now working fine for me, but I am using the the **latest** version.  Make sure Package Control has updated to the latest fixed BH and restart to make sure it is loaded proper.

Also, if you are having issues, you need to provide code and/or steps so I can reproduce the issue, especially since things are working good for me now.

**Comment by ingro** [comment]
Sorry, now I've removed and reinstalled the plugin and everything is working again. I suppose the auto-update didn't work the first time.

Thanks and sorry for bothering!

**Comment by facelessuser** [comment]
No worries.  Just glad it's working now.

**Comment by joemaller** [comment]
Awesome job turning this around so quickly @facelessuser, thank you!
